# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm_register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='category',
            name='order_number',
        ),
    ]
