# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-07-01 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontotal',
            name='transaction_type',
            field=models.CharField(default=b'Unknown', max_length=100),
        ),
    ]
