# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-20 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_register', '0002_transactiontotal_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='enabled',
            field=models.BooleanField(default=b'True'),
        ),
    ]
