# Generated by Django 3.2.12 on 2025-01-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_register', '0004_auto_20230429_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='spanish_name',
            field=models.CharField(default='unset spanish', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='qr_code',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='spanish_name',
            field=models.CharField(default='unset spanish', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='upc_code',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='product',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_count',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax_rate_nonedible',
            field=models.BooleanField(default=False),
        ),
    ]
