# Generated by Django 3.2.12 on 2025-01-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_register', '0005_auto_20250114_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='upc_code',
            field=models.BigIntegerField(default='0'),
        ),
    ]
