# Generated by Django 3.2.12 on 2025-01-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_register', '0007_cashier'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashier',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
